### ISSUE TITLE
stack level too deep when bundle install

### ISSUE THREAD

**Issue by alexey** [radar/by_star#56]
Gemfile:
```gem 'by_star', git: 'git://github.com/radar/by_star```
Got:
```
SystemStackError: stack level too deep
An error occurred while installing by_star (2.2.1), and Bundler cannot continue.
```
Ruby 2.2.0, Rails 4.2.4, OSX Yosemite.

Verbose bundle install show looping on this block till it died on stack level:
```
SystemStackError: stack level too deep
/Users/alexey/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/psych/deprecated.rb:19:in `call'
/Users/alexey/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/psych/deprecated.rb:19:in `block in quick_emit'
/Users/alexey/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2312:in `block (2 levels) in to_yaml'
/Users/alexey/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/psych/coder.rb:36:in `map'
/Users/alexey/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2311:in `block in to_yaml'
```

**Comment by alexey** [comment]
Somehow, by changing in Gemfile to just `gem 'by_star'` 'fix' the problem..
Weird but can be considered as closed

**Comment by radar** [comment]
Seems to be a psych or possibly RVM bug. Recommend reinstalling Ruby with chruby and Ruby-install.
